# 使用场景时，具体场景的值会覆盖default中的值
# demo.yaml 场景文件只为同名的 scripts/demo.py 文件生效，各场景配置的值具体正使用取决于对应的crunner
default:
  username:
  password:
  tester:
  recipients:
  kube_config:
  NAMESPACE:

uat:
  host:
  username:
  password:
  edition:
  NAMESPACE:

dev:
  host:
  username:
  password:
  edition:
  NAMESPACE:
